### ISSUE TITLE
Question: EMSDK installed in shell

### ISSUE THREAD

**Issue by arasouli91** [tbfleming/em-shell#1]
Do you think it is possible to get EMSDK installed in there? So that I can run emcc and compile C code in the browser. I currently have no idea how I could get this to work. I will have to read a lot. If you think it is possible that would also be great if you gave me some idea as to where to start at least.

**Comment by tbfleming** [comment]
It'd need new infrastructure first:
* Multiple processes need to have a shared filesystem
* A port of Python
* Major: a port of nodejs. This part may not be possible.

**Comment by arasouli91** [comment]
Okay, maybe this is not the best route to compiling and executing C code in browser with wasm. 
Not sure how I missed this, but looks like you already figured it out: https://tbfleming.github.io/cib/
Thank you.
